#app.yaml
runtime: python37
env: flex
entrypoint: gunicorn -b :$PORT main:app



env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: 123456789
  CLOUD_SQL_DATABASE_NAME: flask
  CLOUD_SQL_CONNECTION_NAME: devashish-jangid:us-central1:flask